# Generated by Django 4.1 on 2023-02-04 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'permissions': [('check_in', 'Can manage user check in')], 'verbose_name': 'User Details', 'verbose_name_plural': "Users' Details"},
        ),
    ]
