# Generated by Django 4.0.4 on 2022-07-11 23:54

import common_models.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.group')),
                ('finished', models.BooleanField(default=False, verbose_name='Finished Scavenger')),
            ],
            options={
                'verbose_name': 'Scavenger Team',
                'verbose_name_plural': 'Scavenger Teams',
            },
        ),
        migrations.DeleteModel(
            name='NewModel',
        ),
        migrations.AlterModelOptions(
            name='puzzle',
            options={'permissions': [('guess_scavenger_puzzle', 'Can guess for scavenger puzzle')], 'verbose_name': 'Scavenger Puzzle', 'verbose_name_plural': 'Scavenger Puzzles'},
        ),
        migrations.AddField(
            model_name='puzzle',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='puzzle_file',
            field=models.FileField(blank=True, upload_to=common_models.models.puzzle_path),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='puzzle_file_display_filename',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='puzzle_text',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Text'),
        ),
    ]
