# Generated by Django 4.1 on 2022-12-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='checked_in',
            field=models.BooleanField(default=False, verbose_name='Checked In'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='shirt_size',
            field=models.CharField(blank=True, max_length=5, verbose_name='Shirt Size'),
        ),
    ]
