# Generated by Django 4.1 on 2022-12-26 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0002_userdetails_checked_in_userdetails_shirt_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teampuzzleactivity',
            name='locked_out_until',
        ),
    ]
