# Generated by Django 4.0.4 on 2022-07-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0002_team_delete_newmodel_alter_puzzle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='puzzle_file_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='puzzle_file_is_image',
            field=models.BooleanField(default=False),
        ),
    ]
