# Generated by Django 4.0.6 on 2022-07-19 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common_models', '0003_puzzle_puzzle_file_download_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Tag Name')),
            ],
            options={
                'verbose_name': 'Channel Tag',
                'verbose_name_plural': 'Channel Tags',
            },
        ),
        migrations.CreateModel(
            name='DiscordOverwrite',
            fields=[
                ('descriptive_name', models.CharField(blank=True, default='', max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Overwrite ID')),
                ('user_id', models.PositiveBigIntegerField(verbose_name='User or Role ID')),
                ('type', models.IntegerField(choices=[(0, 'Role'), (1, 'Member')])),
                ('allow', models.PositiveBigIntegerField(verbose_name='Allowed Overwrites')),
                ('deny', models.PositiveBigIntegerField(verbose_name='Denied Overwrites')),
            ],
            options={
                'verbose_name': 'Discord Permission Overwrite',
                'verbose_name_plural': 'Discord Permission Overwrites',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='Discord Role ID')),
                ('group_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Discord Role',
                'verbose_name_plural': 'Discord Roles',
            },
        ),
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='Discord Channel ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Discord Channel Name')),
                ('type', models.IntegerField(choices=[(0, 'GUILD_TEXT'), (1, 'DM'), (2, 'GUILD_VOICE'), (3, 'GROUP_DM'), (4, 'GUILD_CATEGORY'), (5, 'GUILD_NEWS'), (6, 'GUILD_STORE'), (10, 'GUILD_NEWS_THREAD'), (11, 'GUILD_PUBLIC_THREAD'), (12, 'GUILD_PRIVATE_THREAD'), (13, 'GUILD_STAGE_VOICE')], verbose_name='Channel Type')),
                ('locked_overwrites', models.ManyToManyField(blank=True, to='common_models.discordoverwrite')),
                ('tags', models.ManyToManyField(blank=True, to='common_models.channeltag')),
                ('unlocked_overwrites', models.ManyToManyField(blank=True, related_name='unlocked_channel_overwrites', to='common_models.discordoverwrite')),
            ],
            options={
                'verbose_name': 'Discord Channel',
                'verbose_name_plural': 'Discord Channels',
                'permissions': [('lock_channels', 'Can lock or unlock discord channels.')],
            },
        ),
    ]
