# Generated by Django 4.1 on 2023-02-10 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0003_alter_roleinvite_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'permissions': [('check_in', 'Can manage user check in'), ('pronoun_group', 'Indicated that a group is a pronoun')], 'verbose_name': 'User Details', 'verbose_name_plural': "Users' Details"},
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='pronouns',
        ),
    ]
