# Generated by Django 4.1 on 2022-12-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0003_remove_teampuzzleactivity_locked_out_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleInvite',
            fields=[
                ('link', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Link')),
                ('role', models.BigIntegerField(verbose_name='Role ID')),
            ],
        ),
    ]
