# Generated by Django 4.0.6 on 2022-07-19 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0004_channeltag_discordoverwrite_role_discordchannel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.RemoveField(
            model_name='team',
            name='finished',
        ),
    ]
