# Generated by Django 4.1 on 2022-12-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0004_roleinvite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscordBingoCards',
        ),
        migrations.AddField(
            model_name='roleinvite',
            name='nick',
            field=models.CharField(default=None, max_length=40, null=True, verbose_name='Nickname'),
        ),
    ]
