# Generated by Django 4.1 on 2022-12-31 04:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common_models', '0005_delete_discordbingocards_roleinvite_nick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Ticket ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('body', models.TextField(max_length=3000, verbose_name='Body')),
                ('status', models.IntegerField(choices=[(0, 'NEW'), (1, 'IN PROGRESS'), (2, 'MORE INFO'), (3, 'CLOSED')], default=0, verbose_name='Status')),
                ('opened', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time Opened')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='Index')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time Created')),
                ('body', models.TextField(max_length=3000, verbose_name='Body')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common_models.ticket')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
