# Generated by Django 4.0.6 on 2022-07-19 23:37

import common_models.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common_models', '0005_alter_team_options_remove_team_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='scavenger_finished',
            field=models.BooleanField(default=False, verbose_name='Finished Scavenger'),
        ),
        migrations.AddField(
            model_name='team',
            name='scavenger_team',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=common_models.models.random_token, max_length=64)),
                ('expiry', models.DateTimeField(default=common_models.models.days5)),
                ('delete_immediately', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Discord ID')),
                ('discord_username', models.CharField(blank=True, max_length=100)),
                ('discriminator', models.IntegerField(blank=True)),
                ('access_token', models.CharField(blank=True, max_length=40)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discord User',
                'verbose_name_plural': 'Discord Users',
            },
        ),
    ]
