# Generated by Django 4.1 on 2023-02-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0006_alter_userdetails_override_nick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='override_nick',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='Name Override'),
        ),
    ]
