# Generated by Django 4.0.6 on 2022-07-19 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common_models', '0006_team_scavenger_finished_team_scavenger_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordBingoCards',
            fields=[
                ('discord_id', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('bingo_card', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Discord Bingo Card',
                'verbose_name_plural': 'Discord Bingo Cards',
            },
        ),
        migrations.CreateModel(
            name='FroshRole',
            fields=[
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Role Name')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.group')),
            ],
            options={
                'verbose_name': 'Frosh Role',
                'verbose_name_plural': 'Frosh Roles',
            },
        ),
        migrations.CreateModel(
            name='UniversityProgram',
            fields=[
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Program Name')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.group')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('pronouns', models.CharField(blank=True, max_length=20, verbose_name='Pronouns')),
                ('invite_email_sent', models.BooleanField(default=False, verbose_name='Invite Email Sent')),
            ],
            options={
                'verbose_name': 'User Details',
                'verbose_name_plural': "Users' Details",
            },
        ),
        migrations.CreateModel(
            name='VirtualTeam',
            fields=[
                ('role_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('num_members', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Virtual Team',
                'verbose_name_plural': 'Virtual Teams',
            },
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': [('change_team_coin', 'Can change the coin amount of a team.'), ('view_team_coin_standings', 'Can view the coin standings of all teams.')], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AddField(
            model_name='team',
            name='coin_amount',
            field=models.BigIntegerField(default=0, verbose_name='Coin Amount'),
        ),
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Hex Color Code'),
        ),
        migrations.AddField(
            model_name='team',
            name='display_name',
            field=models.CharField(default='DEFAULT NAME', max_length=64, unique=True, verbose_name='Team Name'),
            preserve_default=False,
        ),
    ]
