# Generated by Django 4.0.6 on 2022-07-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0007_discordbingocards_froshrole_universityprogram_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puzzle',
            options={'permissions': [('guess_scavenger_puzzle', 'Can guess for scavenger puzzle'), ('manage_scav', 'Can manage scav')], 'verbose_name': 'Scavenger Puzzle', 'verbose_name_plural': 'Scavenger Puzzles'},
        ),
    ]
