# Generated by Django 4.1 on 2023-01-03 17:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0007_alter_ticket_user_alter_ticketcomment_ticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EuchreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(max_length=1, verbose_name='Suit')),
                ('rank', models.IntegerField(verbose_name='rank')),
                ('played', models.BooleanField(default=False, verbose_name='Played')),
            ],
        ),
        migrations.CreateModel(
            name='EuchreGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time Started')),
                ('end', models.DateTimeField(default=None, verbose_name='Time Finished')),
                ('trump', models.CharField(max_length=1, verbose_name='Suit')),
            ],
        ),
        migrations.CreateModel(
            name='EuchrePlayer',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name="Player's Discord ID")),
                ('wins', models.IntegerField(verbose_name='Wins')),
                ('losses', models.IntegerField(verbose_name='Losses')),
            ],
        ),
        migrations.CreateModel(
            name='EuchreTrick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trick', to='common_models.euchrecard')),
                ('opener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trick_opener', to='common_models.euchrecard')),
            ],
        ),
        migrations.CreateModel(
            name='EuchreTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Team ID')),
                ('tricks_won', models.IntegerField(default=0, verbose_name='Tricks Won')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_models.euchregame')),
                ('going_alone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common_models.euchreplayer')),
            ],
        ),
        migrations.AddField(
            model_name='euchreplayer',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common_models.euchreteam'),
        ),
        migrations.AddField(
            model_name='euchregame',
            name='current_trick',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_models.euchretrick'),
        ),
        migrations.AddField(
            model_name='euchregame',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_models.euchreplayer'),
        ),
        migrations.AddField(
            model_name='euchregame',
            name='declarer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_declarer', to='common_models.euchreteam'),
        ),
        migrations.AddField(
            model_name='euchregame',
            name='next_dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_dealer', to='common_models.euchreplayer'),
        ),
        migrations.AddField(
            model_name='euchregame',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_winner', to='common_models.euchreteam'),
        ),
        migrations.AddField(
            model_name='euchrecard',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='common_models.euchreplayer'),
        ),
    ]
