# Generated by Django 4.1 on 2023-01-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0008_euchrecard_euchregame_euchreplayer_euchretrick_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euchreplayer',
            name='losses',
            field=models.IntegerField(default=0, verbose_name='Losses'),
        ),
        migrations.AlterField(
            model_name='euchreplayer',
            name='wins',
            field=models.IntegerField(default=0, verbose_name='Wins'),
        ),
    ]
