# Generated by Django 4.1 on 2023-03-30 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0009_alter_pronoun_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='stream_branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_puzzle', to='common_models.puzzlestream'),
        ),
        migrations.AddField(
            model_name='puzzlestream',
            name='default',
            field=models.BooleanField(default=True),
        ),
    ]
