# Generated by Django 4.1 on 2023-01-03 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0009_alter_euchreplayer_losses_alter_euchreplayer_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euchreteam',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common_models.euchregame'),
        ),
    ]
