# Generated by Django 4.0.6 on 2022-08-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0009_discordguild'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discordguild',
            options={'permissions': [], 'verbose_name': 'Discord Guild', 'verbose_name_plural': 'Discord Guilds'},
        ),
        migrations.AddField(
            model_name='discordguild',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
