# Generated by Django 4.0.6 on 2022-08-05 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0010_alter_discordguild_options_discordguild_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleStream',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Scavenger Puzzle Stream',
                'verbose_name_plural': 'Scavenger Puzzle Streams',
            },
        ),
        migrations.CreateModel(
            name='TeamPuzzleActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_start_at', models.DateTimeField(auto_now=True)),
                ('puzzle_completed_at', models.DateTimeField(default=None, null=True)),
                ('locked_out_until', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='puzzles',
            field=models.ManyToManyField(through='common_models.TeamPuzzleActivity', to='common_models.puzzle'),
        ),
        migrations.AddField(
            model_name='team',
            name='scavenger_locked_out_until',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='teampuzzleactivity',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_models.puzzle'),
        ),
        migrations.AddField(
            model_name='teampuzzleactivity',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_models.team'),
        ),
        migrations.CreateModel(
            name='PuzzleGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=100)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_models.teampuzzleactivity')),
            ],
        ),
    ]
