# Generated by Django 4.1 on 2023-01-03 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0010_alter_euchreteam_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='euchretrick',
            name='selection',
            field=models.BooleanField(default=False, verbose_name='Trump Selection'),
        ),
        migrations.AlterField(
            model_name='euchregame',
            name='declarer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_declarer', to='common_models.euchreteam'),
        ),
        migrations.AlterField(
            model_name='euchregame',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_winner', to='common_models.euchreteam'),
        ),
    ]
