# Generated by Django 4.1 on 2023-01-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0011_euchretrick_selection_alter_euchregame_declarer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euchregame',
            name='end',
            field=models.DateTimeField(default=None, null=True, verbose_name='Time Finished'),
        ),
    ]
