# Generated by Django 4.1 on 2023-04-05 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0011_alter_userdetails_override_nick'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magiclink',
            options={'permissions': [('view_links', 'Can view magic links')]},
        ),
    ]
