# Generated by Django 4.0.6 on 2022-08-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0011_puzzlestream_teampuzzleactivity_team_puzzles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
