# Generated by Django 4.1 on 2023-01-03 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0012_alter_euchregame_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='euchregame',
            name='extra_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common_models.euchrecard'),
        ),
    ]
