# Generated by Django 4.0.6 on 2022-08-05 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0012_puzzle_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='stream',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='common_models.puzzlestream'),
            preserve_default=False,
        ),
    ]
