# Generated by Django 4.1 on 2023-04-05 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0012_alter_magiclink_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discorduser',
            options={'permissions': [('view_discord_nicks', 'Can view Discord info for users'), ('manage_discord_nicks', 'Can manage Discord info for users')], 'verbose_name': 'Discord User', 'verbose_name_plural': 'Discord Users'},
        ),
    ]
