# Generated by Django 4.1 on 2023-01-03 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0013_euchregame_extra_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='euchregame',
            name='selector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selector', to='common_models.euchreplayer'),
        ),
        migrations.AddField(
            model_name='euchretrick',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='euchretrick',
            name='opener',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trick_opener', to='common_models.euchrecard'),
        ),
    ]
