# Generated by Django 4.1.7 on 2023-05-15 00:10

import common_models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0014_team_logo_alter_discorduser_discord_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=common_models.models.logo_path),
        ),
    ]
