# Generated by Django 4.1 on 2023-01-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0014_euchregame_selector_euchretrick_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='euchrecard',
            name='played',
        ),
    ]
