# Generated by Django 4.1.7 on 2023-05-17 16:56

import common_models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0015_alter_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='scav_tree',
            field=models.ImageField(blank=True, null=True, upload_to=common_models.models.tree_path),
        ),
    ]
