# Generated by Django 4.0.6 on 2022-08-08 21:15

import common_models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0016_alter_teampuzzleactivity_options_puzzle_secret_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='secret_id',
            field=models.CharField(default=common_models.models.random_puzzle_secret_id, max_length=64, unique=True),
        ),
    ]
