# Generated by Django 4.1.7 on 2023-05-20 00:20

import common_models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0016_team_scav_tree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='scav_tree',
            field=models.FileField(blank=True, null=True, upload_to=common_models.models.tree_path),
        ),
    ]
