# Generated by Django 4.1 on 2022-08-16 23:28

import common_models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0017_alter_puzzle_secret_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlestream',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='secret_id',
            field=models.SlugField(default=common_models.models.random_puzzle_secret_id, max_length=64, unique=True),
        ),
    ]
