# Generated by Django 4.1 on 2022-08-16 23:58

import common_models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0018_puzzlestream_enabled_alter_puzzle_secret_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleVerificationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to=common_models.models._puzzle_verification_photo_upload_path)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='puzzle',
            name='require_photo_upload',
            field=models.BooleanField(default=True),
        ),
    ]
