# Generated by Django 4.1 on 2023-01-06 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0018_remove_euchreplayer_losses_remove_euchreplayer_wins'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobertEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(verbose_name='Robert Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_models.discorduser')),
            ],
        ),
    ]
