# Generated by Django 4.1 on 2023-01-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0019_robertentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robertentry',
            name='user',
            field=models.PositiveBigIntegerField(verbose_name='User ID'),
        ),
    ]
