# Generated by Django 4.1 on 2022-08-18 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0020_alter_puzzle_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PuzzleVerificationPhoto',
            new_name='VerificationPhoto',
        ),
        migrations.AddField(
            model_name='teampuzzleactivity',
            name='verification_photo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common_models.verificationphoto'),
        ),
    ]
