# Generated by Django 4.1.7 on 2023-05-22 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0020_alter_discordrole_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordchannel',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common_models.team'),
        ),
    ]
