# Generated by Django 4.1 on 2023-01-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0021_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discordchannel',
            options={'permissions': [('lock_channels', 'Can lock or unlock discord channels.'), ('purge_channels', 'Can purge a discord channel of all messages')], 'verbose_name': 'Discord Channel', 'verbose_name_plural': 'Discord Channels'},
        ),
        migrations.AlterModelOptions(
            name='discordguild',
            options={'permissions': [('create_role', 'Allows a user to create discord roles'), ('create_channel', 'Allows a user to create discord channels')], 'verbose_name': 'Discord Guild', 'verbose_name_plural': 'Discord Guilds'},
        ),
        migrations.AlterModelOptions(
            name='roleinvite',
            options={'permissions': [('create_invite', 'Can create invites to the discord server')], 'verbose_name': 'Role Invite', 'verbose_name_plural': 'Role Invites'},
        ),
    ]
