# Generated by Django 4.1.7 on 2023-05-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0021_discordchannel_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='int_frosh_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='waiver_completed',
            field=models.BooleanField(default=False, verbose_name='Waiver Completed'),
        ),
    ]
