# Generated by Django 4.1 on 2022-08-25 19:21

import common_models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0021_rename_puzzleverificationphoto_verificationphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=common_models.models.scavenger_qr_code_path),
        ),
    ]
