# Generated by Django 4.1.7 on 2023-07-16 17:04

from django.db import migrations, models
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0022_userdetails_int_frosh_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InclusivityPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('permissions', models.IntegerField()),
                ('open_time', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
