# Generated by Django 4.1 on 2023-02-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0023_alter_puzzle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationphoto',
            options={'permissions': [('photo_api', 'Can create verification photos through the API')], 'verbose_name': 'Verification Photo', 'verbose_name_plural': 'Verification Photos'},
        ),
    ]
