# Generated by Django 4.1.7 on 2023-07-16 17:19

import common_models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0023_inclusivitypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclusivitypage',
            name='file',
            field=models.FileField(upload_to=common_models.models.inclusivity_path),
        ),
    ]
