# Generated by Django 4.1 on 2022-08-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0023_rename_role_discordrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='order',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
