# Generated by Django 4.1.7 on 2023-07-26 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common_models', '0024_alter_inclusivitypage_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('desc', models.CharField(max_length=1000, verbose_name='Description')),
                ('flags', models.CharField(max_length=5, verbose_name='Flags')),
                ('max_facils', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FacilShiftSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_models.facilshift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
