# Generated by Django 4.1 on 2022-08-31 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0025_booleansetting_alter_puzzleguess_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booleansetting',
            options={'verbose_name': 'Boolean Setting', 'verbose_name_plural': 'Boolean Settings'},
        ),
    ]
