# Generated by Django 4.1.7 on 2023-07-26 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0025_facilshift_facilshiftsignup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilshift',
            options={'permissions': [('facil_signup', 'Can sign up for shifts')], 'verbose_name': 'Facil Shift', 'verbose_name_plural': 'Facil Shifts'},
        ),
    ]
