# Generated by Django 4.1.7 on 2023-07-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0026_alter_facilshift_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilshift',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Shift ID'),
        ),
    ]
