# Generated by Django 4.1 on 2022-08-31 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0026_alter_booleansetting_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='trade_up_enabled_for_team',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='trade_up_team',
            field=models.BooleanField(default=True),
        ),
    ]
