# Generated by Django 4.1.7 on 2023-07-26 01:35

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0027_alter_facilshift_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilshift',
            name='end',
            field=django_unixdatetimefield.fields.UnixDateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='facilshift',
            name='start',
            field=django_unixdatetimefield.fields.UnixDateTimeField(null=True),
        ),
    ]
