# Generated by Django 4.1 on 2022-08-31 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0027_team_trade_up_enabled_for_team_team_trade_up_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTradeUpActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_models.team')),
                ('verification_photo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common_models.verificationphoto')),
            ],
            options={
                'verbose_name': 'Team Trade Up Activity',
                'verbose_name_plural': 'Team Trade Up Activities',
            },
        ),
    ]
