# Generated by Django 4.1 on 2022-09-02 03:19

import common_models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0028_teamtradeupactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='magiclink',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=common_models.models.magic_link_qr_code_path),
        ),
    ]
