# Generated by Django 4.1 on 2022-09-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0029_magiclink_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtradeupactivity',
            name='object_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
