# Generated by Django 4.1.7 on 2023-08-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0029_team_free_hints'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='breakfast',
            field=models.BooleanField(default=False, verbose_name='Breakfast Requested'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='breakfast_paid',
            field=models.BooleanField(default=False, verbose_name='Breakfast Paid'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='brightspace_completed',
            field=models.BooleanField(default=False, verbose_name='Brightspace Training Completed'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='contract',
            field=models.BooleanField(default=False, verbose_name='Contract Signed'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='hardhat',
            field=models.BooleanField(default=False, verbose_name='Hardhat Requested'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='hardhat_paid',
            field=models.BooleanField(default=False, verbose_name='Hardhat Paid'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='prc_completed',
            field=models.BooleanField(default=False, verbose_name='PRC Completed'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='rafting',
            field=models.BooleanField(default=False, verbose_name='Rafting Requested'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='rafting_paid',
            field=models.BooleanField(default=False, verbose_name='Rafting Paid'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='training_completed',
            field=models.BooleanField(default=False, verbose_name='In Person Training Completed'),
        ),
    ]
