# Generated by Django 4.1.10 on 2023-08-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0030_userdetails_breakfast_userdetails_breakfast_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='allergies',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Allergies'),
        ),
    ]
