# Generated by Django 4.1.10 on 2023-08-31 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0031_userdetails_allergies'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='sweater_size',
            field=models.CharField(blank=True, max_length=5, verbose_name='Sweater Size'),
        ),
    ]
