# Generated by Django 4.1.7 on 2023-12-15 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0032_userdetails_sweater_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleinvite',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common_models.userdetails'),
        ),
    ]
