# Generated by Django 4.1.7 on 2024-03-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0033_roleinvite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordchannel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Discord Channel Base Name'),
        ),
    ]
