# Generated by Django 4.1.7 on 2024-03-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0034_alter_discordchannel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordchannel',
            name='basename',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Discord Channel Base Name'),
        ),
        migrations.AlterField(
            model_name='discordchannel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Discord Channel Name'),
        ),
    ]
