# Generated by Django 4.1.7 on 2024-03-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0035_discordchannel_basename_alter_discordchannel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='discord_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Discord Name'),
        ),
    ]
