# Generated by Django 4.1.7 on 2024-03-04 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0036_team_discord_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordchannel',
            name='basename',
        ),
    ]
