# Generated by Django 4.2.7 on 2024-03-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0037_remove_discordchannel_basename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
    ]
