# Generated by Django 4.1.7 on 2024-03-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0040_faqpage_lockoutperiod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilshift',
            options={'permissions': [('facil_signup', 'Can sign up for shifts'), ('calendar_manage', 'Can manage calendars')], 'verbose_name': 'Facil Shift', 'verbose_name_plural': 'Facil Shifts'},
        ),
    ]
