# Generated by Django 4.1.7 on 2024-03-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0041_alter_facilshift_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'permissions': [('announcement_manage', 'Can manage announcements')], 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
    ]
