# Generated by Django 4.2.11 on 2024-04-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0045_teampuzzleactivity_completed_bitmask'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='stream_puzzle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common_models.puzzle'),
        ),
    ]
