# Generated by Django 4.2.11 on 2024-04-08 15:52

import common_models.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0046_puzzle_stream_puzzle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='qr_code',
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=common_models.models.scavenger_qr_code_path)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_models.puzzle')),
            ],
        ),
    ]
