# Generated by Django 4.1.7 on 2024-04-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0048_facilshiftsignup_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilshift',
            options={'permissions': [('facil_signup', 'Can sign up for shifts'), ('calendar_manage', 'Can manage calendars'), ('shift_manage', 'Can manage facil shifts'), ('attendance_manage', 'Can manage facil shift attendance'), ('report_manage', 'Can manage reports')], 'verbose_name': 'Facil Shift', 'verbose_name_plural': 'Facil Shifts'},
        ),
    ]
