# Generated by Django 4.1.13 on 2024-05-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0050_alter_discordguild_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emote', models.CharField(max_length=64, verbose_name='Emote')),
                ('role', models.PositiveBigIntegerField(verbose_name='Role id')),
                ('message', models.PositiveBigIntegerField(verbose_name='Message id')),
            ],
        ),
    ]
