# Generated by Django 4.1.13 on 2024-06-04 02:28

import common_models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0052_siteimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='image',
            field=models.ImageField(null=True, upload_to=common_models.models.img_path),
        ),
    ]
