# Generated by Django 4.1.13 on 2024-06-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0053_siteimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqpage',
            name='restricted',
            field=models.BooleanField(default=False, verbose_name='Restricted'),
        ),
    ]
