# Generated by Django 4.1.13 on 2024-06-09 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common_models', '0054_faqpage_restricted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqpage',
            name='restricted',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
