# Generated by Django 4.1.13 on 2024-06-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0056_remove_faqpage_restricted_group_faqpage_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='puzzle_file_is_link',
            field=models.BooleanField(default=False),
        ),
    ]
