# Generated by Django 4.1.13 on 2024-06-11 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0057_puzzle_puzzle_file_is_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='puzzle_file_is_link',
            new_name='puzzle_is_link',
        ),
    ]
