# Generated by Django 4.1.13 on 2024-06-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common_models', '0059_userdetails_discord_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqpage',
            name='restricted',
            field=models.ManyToManyField(blank=True, null=True, to='auth.group'),
        ),
    ]
