# Generated by Django 4.1.13 on 2024-06-21 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common_models', '0060_alter_faqpage_restricted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqpage',
            name='restricted',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='stream_puzzle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puzzle_opener', to='common_models.puzzle'),
        ),
    ]
