# Generated by Django 4.2 on 2024-07-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0062_alter_verificationphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='answer',
            field=models.CharField(max_length=400),
        ),
    ]
