# Generated by Django 4.2 on 2024-07-05 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0063_alter_puzzle_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puzzle',
            options={'permissions': [('guess_scavenger_puzzle', 'Can guess for scavenger puzzle'), ('manage_scav', 'Can manage scav'), ('bypass_scav_rules', 'Bypasses all scav rules'), ('disable_scav_save', 'Stops puzzles from being saved when completed'), ('lock_scav', 'Can lock scav')], 'verbose_name': 'Scavenger Puzzle', 'verbose_name_plural': 'Scavenger Puzzles'},
        ),
    ]
