# Generated by Django 4.2.14 on 2024-07-18 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common_models', '0064_alter_puzzle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilshift',
            options={'permissions': [('facil_signup', 'Can sign up for shifts'), ('calendar_manage', 'Can manage calendars'), ('shift_manage', 'Can manage facil shifts'), ('attendance_manage', 'Can manage facil shift attendance'), ('report_manage', 'Can manage reports'), ('attendance_admin', 'Can manage attendance for restricted shifts')], 'verbose_name': 'Facil Shift', 'verbose_name_plural': 'Facil Shifts'},
        ),
        migrations.AddField(
            model_name='facilshift',
            name='administrative',
            field=models.BooleanField(blank=True, default=False, verbose_name='Administrative'),
        ),
        migrations.AddField(
            model_name='facilshift',
            name='checkin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facilshift',
            name='end',
            field=django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facilshift',
            name='start',
            field=django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True),
        ),
    ]
