# Generated by Django 4.2.14 on 2024-07-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0065_alter_facilshift_options_facilshift_administrative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilshift',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type'),
        ),
    ]
