# Generated by Django 4.2.14 on 2024-08-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0069_puzzlestream_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='room',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Room Number'),
        ),
    ]
