# Generated by Django 4.2.14 on 2024-08-12 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0070_team_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockoutperiod',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common_models.puzzlestream'),
        ),
    ]
