# Generated by Django 4.2.14 on 2024-08-12 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0071_lockoutperiod_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'permissions': [('check_in', 'Can manage user check in'), ('frosh_list', 'Can access frosh list')], 'verbose_name': 'User Details', 'verbose_name_plural': "Users' Details"},
        ),
    ]
