# Generated by Django 4.2.14 on 2024-08-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0072_alter_userdetails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlestream',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
