# Generated by Django 4.2.14 on 2024-08-21 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0073_puzzlestream_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilshiftsignup',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='common_models.facilshift'),
        ),
    ]
