# Generated by Django 4.2.14 on 2024-08-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0074_alter_facilshiftsignup_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='invalidate_tree',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='tree_cache',
            field=models.TextField(default='{}'),
        ),
    ]
