# Generated by Django 4.2.14 on 2024-08-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0075_team_invalidate_tree_team_tree_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tree_cache',
            field=models.TextField(default=''),
        ),
    ]
