# Generated by Django 4.2.14 on 2024-08-26 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0076_alter_team_tree_cache'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='room',
            new_name='_room',
        ),
        migrations.CreateModel(
            name='TeamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('room', models.CharField(max_length=64, verbose_name='Room Number')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_models.team')),
            ],
        ),
    ]
