# Generated by Django 4.2.15 on 2024-08-31 20:19

import common_models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0078_alter_userdetails_shirt_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqpage',
            name='img',
            field=models.ImageField(null=True, upload_to=common_models.models.img_path),
        ),
    ]
