# Generated by Django 5.1.4 on 2025-02-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0081_alter_team_scavenger_locked_out_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='euchrecard',
            name='player',
        ),
        migrations.RemoveField(
            model_name='euchretrick',
            name='opener',
        ),
        migrations.RemoveField(
            model_name='euchretrick',
            name='highest',
        ),
        migrations.RemoveField(
            model_name='euchregame',
            name='extra_card',
        ),
        migrations.RemoveField(
            model_name='euchregame',
            name='current_trick',
        ),
        migrations.RemoveField(
            model_name='euchregame',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='euchregame',
            name='declarer',
        ),
        migrations.RemoveField(
            model_name='euchregame',
            name='next_dealer',
        ),
        migrations.RemoveField(
            model_name='euchregame',
            name='selector',
        ),
        migrations.RemoveField(
            model_name='euchregame',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='euchreteam',
            name='game',
        ),
        migrations.RemoveField(
            model_name='euchreplayer',
            name='team',
        ),
        migrations.RemoveField(
            model_name='euchreteam',
            name='going_alone',
        ),
        migrations.DeleteModel(
            name='RobertEntry',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='EuchreCard',
        ),
        migrations.DeleteModel(
            name='EuchreTrick',
        ),
        migrations.DeleteModel(
            name='EuchreGame',
        ),
        migrations.DeleteModel(
            name='EuchrePlayer',
        ),
        migrations.DeleteModel(
            name='EuchreTeam',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TicketComment',
        ),
    ]
