# Generated by Django 5.1.4 on 2025-02-16 17:37

import common_models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0082_remove_euchrecard_player_remove_euchretrick_opener_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facilshift',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facilshift',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inclusivitypage',
            name='open_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lockoutperiod',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lockoutperiod',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='magiclink',
            name='expiry',
            field=models.DateTimeField(default=common_models.models.days5),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='puzzleguess',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teampuzzleactivity',
            name='puzzle_completed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='teampuzzleactivity',
            name='puzzle_start_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teamtradeupactivity',
            name='entered_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='verificationphoto',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
