# Generated by Django 5.1.4 on 2025-02-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0083_alter_announcement_created_alter_discorduser_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='int_frosh_id',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
    ]
