# Generated by Django 5.1.4 on 2025-07-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0084_alter_userdetails_int_frosh_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilshift',
            name='max_facils_per_team',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facilshift',
            name='signups_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
