# Generated by Django 5.1.4 on 2025-07-10 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0086_randallblocked_randalllocation_randallbooking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='randallbooking',
            options={'permissions': [('book_randall', 'Can create bookings'), ('manage_randall', 'Can manage bookings'), ('locate_randall', 'Can send location data through the API'), ('view_randall', 'Can view randall')]},
        ),
    ]
