# Generated by Django 5.1.4 on 2025-07-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0087_alter_randallbooking_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='wt_waiver_completed',
            field=models.BooleanField(default=False, verbose_name='WT Waiver Completed'),
        ),
    ]
