# Generated by Django 5.1.4 on 2025-07-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0088_userdetails_wt_waiver_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='access_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
