# Generated by Django 5.1.4 on 2025-08-16 21:26

import common_models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0089_alter_discorduser_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('image', models.ImageField(null=True, upload_to=common_models.models.img_path)),
                ('footer', models.BooleanField(default=False)),
                ('link', models.CharField(max_length=256, verbose_name='Link')),
            ],
        ),
    ]
