# Generated by Django 5.1.4 on 2025-08-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0090_sponsorlogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorlogo',
            name='link',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Link'),
        ),
    ]
